name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: DeterminateSystems/nix-installer-action@v22
        with:
          determinate: false
          github-token: ''
      - name: Check flake
        run: nix flake check
      - name: Build package
        run: nix build .
      - name: Update MoonBit registry
        run: nix develop -c moon update
      - name: Check MoonBit
        run: nix develop -c moon check --warn-list +73
      - name: Test MoonBit
        run: nix develop -c moon test
      - name: Check native stdio package
        run: nix develop -c moon check --target native --warn-list +73
